.TH "rai" "1"
.SH NAME
rai \- random image generator
.SH "SYNOPSIS"
.SY rai
.OP \-h
.OP \-W width
.OP \-H height
.OP \-s seed
.OP \-n slt
.YS

.SH "USAGE"
.PP
rai will generate a random image and print it to stdout in the ppm format.
.SH "OPTIONS"
.TP
.B \-W width
set width of the image
.TP
.B \-H height
set height of the image
.TP
.B \-s seed
set seed for the image
.TP
.B \-n l / s / t
turn off
\fBl\fPines, \fBs\fPquares or \fBt\fPriangles
.SH "EXAMPLES"
.EX
rai -W 1000 -H 1000 -s 3000 \\
	| convert PPM:- \\
		-fill white \\
		-font /usr/local/share/fonts/ProggyVector\\ Regular.ttf \\
		-pointsize 75 \\
		-gravity center \\
		-annotate 0 "rai(1)" \\
		rai.png
.EE
